services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_vector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: